---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ozelpiya/public_html/
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R style.css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    

    
